<?php
/**
 * Created by PhpStorm.
 * User: quangthinh
 * Date: 5/26/2017
 * Time: 12:40 AM
 */

namespace quangthinh\yii\common\columns;


use yii\grid\DataColumn;
use yii\helpers\Html;

class ImageColumn extends DataColumn
{
    public $format = 'raw';
    public $imageOptions = [];
    public $urlCreator;
    public $baseUrl = '@web';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (empty($this->urlCreator)) {
            $attribute = $this->attribute;
            $baseUrl = $this->baseUrl;

            $this->urlCreator = function ($model) use ($baseUrl, $attribute) {
                return $baseUrl . $model->$attribute;
            };
        }

        if (empty($this->value)) {
            $urlCreator = $this->urlCreator;
            $imageOptions = $this->imageOptions;
            $this->value = function ($model) use ($urlCreator, $imageOptions) {
                return Html::img($urlCreator($model), $imageOptions);
            };
        }
    }
}