<?php
/**
 * Created by PhpStorm.
 * User: quangthinh
 * Date: 5/23/2017
 * Time: 11:15 AM
 */

namespace quangthinh\yii\common\behaviors;

use kartik\datecontrol\Module;
use Yii;

class TimestampBehavior extends \yii\behaviors\TimestampBehavior
{
    public $dateControl = 'datecontrol';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!$this->value) {
            $this->value = function () {
                /**
                 * @var Module $control
                 */
                $control = Yii::$app->getModule($this->dateControl);
                return (new \DateTime('now', new \DateTimeZone($control->getSaveTimezone())))->format('Y-m-d H:i:s');
            };
        }
    }
}