<?php
/**
 * Created by PhpStorm.
 * User: quangthinh
 * Date: 5/25/2017
 * Time: 11:58 PM
 */

namespace quangthinh\yii\common\rules;

use yii\base\InvalidConfigException;
use yii\db\ActiveRecord;
use yii\helpers\Inflector;
use yii\web\UrlRule;


/**
 * Class UrlSlugRule
 * @package quangthinh\yii\common
 *
 * beta
 *
 *       [
 *         'class' => 'common\UrlSlugRule',
 *         'modelClass' => 'common\models\User',
 *         'slugAttribute' => 'username',
 *         'pattern' => 'user/<id:\d+>/<slug:[^/]+>',
 *         'route' => 'user/default/view',
 *       ],
 */
class UrlSlugRule extends UrlRule
{
    public $modelClass;
    public $slugAttribute = 'title';
    public $slugParamName = 'slug';

    protected function findActiveRecord($route, $params) {
        if (empty($params['id'])) return null;

        /**
         * @var $class ActiveRecord
         */
        $class = $this->modelClass;

        $id = $params['id'];
        $model = $class::findOne($id);
        return $model;
    }

    public function init()
    {
        if (!is_subclass_of($this->modelClass, ActiveRecord::className())) {
            throw new InvalidConfigException('$modelClass must be instance of ActiveRecord');
        }

        return parent::init(); // TODO: Change the autogenerated stub
    }

    public function createUrl($manager, $route, $params)
    {
        $model = $this->findActiveRecord($route, $params);
        if ($model) {
            $slug = $this->slugAttribute;
            $params[$this->slugParamName] = Inflector::slug($model->{$slug});
        }

        return parent::createUrl($manager, $route, $params); // TODO: Change the autogenerated stub
    }
}